// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADYUoZwgVf-ZUaqX7TtZspc-nHWP1oAd4',
    appId: '1:550746434079:web:e36cc4893fcc7ed3fc832a',
    messagingSenderId: '550746434079',
    projectId: 'flutter-app-firebas',
    authDomain: 'flutter-app-firebas.firebaseapp.com',
    storageBucket: 'flutter-app-firebas.appspot.com',
    measurementId: 'G-S4GYTX5PT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHnEmeGwJMxKaMKTfPqi1zjMPQ0qvp24',
    appId: '1:550746434079:android:cff8ae748754e549fc832a',
    messagingSenderId: '550746434079',
    projectId: 'flutter-app-firebas',
    storageBucket: 'flutter-app-firebas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Ztg_Y-Evn-4Q3LKLwSKBhw4Cl_JL2eQ',
    appId: '1:550746434079:ios:58527569f537c731fc832a',
    messagingSenderId: '550746434079',
    projectId: 'flutter-app-firebas',
    storageBucket: 'flutter-app-firebas.appspot.com',
    iosClientId: '550746434079-4sgn5479qkpco64s4jcku5miqaph3os9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
