// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi3r9xfXE7SgKeDUl0rArcEDHhfqE7qRE',
    appId: '1:18003326107:web:22265f745da1378d1e423e',
    messagingSenderId: '18003326107',
    projectId: 'flutter-app-auth-57399',
    authDomain: 'flutter-app-auth-57399.firebaseapp.com',
    storageBucket: 'flutter-app-auth-57399.appspot.com',
    measurementId: 'G-8SFYLM35YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4H1pC9hZW669_uAeqosvYrhrbSB1-8k',
    appId: '1:18003326107:android:f133a9d74495cac71e423e',
    messagingSenderId: '18003326107',
    projectId: 'flutter-app-auth-57399',
    storageBucket: 'flutter-app-auth-57399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvPF3fEkGP308NVTusvsAXTPzZE3s3T4',
    appId: '1:18003326107:ios:f348be14283d72331e423e',
    messagingSenderId: '18003326107',
    projectId: 'flutter-app-auth-57399',
    storageBucket: 'flutter-app-auth-57399.appspot.com',
    iosClientId: '18003326107-vg6bdo7isskf017aa7sgfof4o10rrq63.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
